# Generated by Django 4.0.2 on 2022-03-24 01:12

from django.db import migrations, models
import django.db.models.deletion
import dokumint.models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='image',
            field=models.ImageField(upload_to=dokumint.models.get_file_path, verbose_name='File'),
        ),
        migrations.CreateModel(
            name='ProjectDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(blank=True, max_length=255, null=True)),
                ('proj_desc', models.TextField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('img_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('certifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumint.certifier')),
            ],
        ),
    ]
