# Generated by Django 4.0.2 on 2022-03-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumint', '0002_alter_receiver_image_projectdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
