# Generated by Django 3.1.7 on 2022-03-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumint', '0003_receiver_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifier',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectdesc',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
